BUILD_DIR := build

# Remove stale per-class JSON (classes that no longer exist in a source).
#
# ``json/`` holds each source's OWN classes: base sources (va-core,
# domain-entities) share ./json; each ``XXX-profile-source.yaml`` writes to
# ``XXX/json``. ``def/`` is a full import-closure regenerated by ``y2t`` on
# every build, so it is intentionally not pruned here — removing a class
# requires a ``make clean`` (see the top-level README note).

BASE_SOURCES := $(filter-out %-profile-source.yaml,$(wildcard *-source.yaml))
BASE_CLASS_FILES := $(BASE_SOURCES:%-source.yaml=${BUILD_DIR}/%.classes)
BASE_KEEP := $(foreach c,$(shell cat ${BASE_CLASS_FILES} 2>/dev/null),json/$(c))
PROFILE_SOURCES := $(wildcard *-profile-source.yaml)

.DEFAULT: prune

prune: prune-base prune-profiles

# Base sources share ./json.
prune-base: STALE = $(filter-out ${BASE_KEEP},$(wildcard json/*))
prune-base:
	$(if ${STALE},rm ${STALE})

# Each profile's own classes live under XXX/json.
prune-profiles:
	@for src in ${PROFILE_SOURCES}; do \
	  ns=$${src%-profile-source.yaml}; \
	  stem=$${src%-source.yaml}; \
	  [ -d "$$ns/json" ] || continue; \
	  keep=" $$(cat ${BUILD_DIR}/$$stem.classes 2>/dev/null | tr '\n' ' ') "; \
	  for f in "$$ns"/json/*; do \
	    [ -e "$$f" ] || continue; \
	    case "$$keep" in *" $$(basename $$f) "*) ;; *) echo "rm $$f"; rm "$$f";; esac; \
	  done; \
	done
